// Dynamic Hub Data feed generated by real-time automated research.
// This database is automatically generated 5 times per day.

const DYNAMIC_HUB_DATA = {
  "ticker": [
    "⚽ Potter's advanced media division sets up at Bosön press center",
    "🌍 Norway national team trains behind closed doors at Ullevaal Stadion",
    "💪 Viktor Gyökeres continues to lead intense training drills in the Dallas camp.",
    "🚑 Starfelt completes full fitness registers; Potter confirms 100% squad availability.",
    "📈 Sweden WC opener ticket allocation sells out completely in under 12 minutes."
  ],
  "timeline": {
    "2026-05-26": {
      "1": {
        "timeLabel": "07:00",
        "name": "Breakfast Camp Report",
        "articles": [
          {
            "id": "dyn_swe_20260526_1",
            "category": "sweden",
            "type": "News",
            "title": "Sweden squad packs bags and prepares for Wednesday gather at Bosön",
            "bullets": [
              "Graham Potter's 26-man roster completes travel arrangements to Stockholm.",
              "Players to check in by Wednesday morning at the Bosön national training complex.",
              "Captain Victor Lindelöf: 'Stockholm, see you tomorrow! Roster is extremely motivated.'"
            ],
            "summary": "Ahead of tomorrow's official camp gathering, Swedish squad players are traveling from their domestic and European clubs to Stockholm. The primary base will be Lidingö's elite training complex at Bosön, preparing for the initial four-day training and tactical brief phase.",
            "author": "Marcus Wulcan (Aftonbladet)",
            "readTime": "3 min",
            "tag": "Camp Gathering",
            "relatedPlayers": []
          },
          {
            "id": "dyn_opp_20260526_1",
            "category": "opponent",
            "type": "Scouting",
            "title": "Tunisia squad performs high-altitude stamina workouts in Tabarka base",
            "bullets": [
              "Carthage Eagles focus on rapid defensive counter transitions under Jalel Kadri.",
              "Midfielder Ellyes Skhiri highlights their robust tactical shape to the media.",
              "Scouts observe Tunisia utilizing compact 4-1-4-1 layouts in custom scrimmages."
            ],
            "summary": "Sweden's Group F opponent Tunisia is wrapping up their secondary preparation phase in the mountainous region of Tabarka. Manager Jalel Kadri has emphasized defensive shape, looking to crowd midfield spaces and launch lightning-fast counters. Eintracht Frankfurt's Ellyes Skhiri remains their tactical anchor.",
            "author": "CBS Sports Golazo Feed",
            "readTime": "3 min",
            "tag": "Opponent scouting",
            "relatedPlayers": []
          }
        ]
      },
      "2": {
        "timeLabel": "11:00",
        "name": "Press Briefing",
        "articles": [
          {
            "id": "dyn_swe_20260526_2",
            "category": "sweden",
            "type": "News",
            "title": "Potter's advanced media division sets up at Bosön press center",
            "bullets": [
              "Svenska FA builds primary mixed zone facilities at Bosön headquarters.",
              "Over 120 accredited media representatives arrive to cover training.",
              "Svensk Fotboll announces structured daily press briefing timetable."
            ],
            "summary": "Svensk Fotboll's media team completed mixed-zone setup at Bosön this morning, preparing for tomorrow's official media blitz. Coach Graham Potter will conduct the inaugural press conference on Wednesday to establish camp guidelines.",
            "author": "Olof Lundh (Fotbollskanalen)",
            "readTime": "3 min",
            "tag": "Media Blitz",
            "relatedPlayers": []
          },
          {
            "id": "dyn_opp_20260526_2",
            "category": "opponent",
            "type": "Scouting",
            "title": "Norway national team trains behind closed doors at Ullevaal Stadion",
            "bullets": [
              "Ståle Solbakken hides tactical set-piece drills ahead of Sweden warm-up.",
              "Erling Haaland works on penalty box movements against low block setups.",
              "Norwegian FA reports away tickets for Swedish fans are completely sold out."
            ],
            "summary": "Ahead of the Scandinavian derby on June 1, Norway's head coach Ståle Solbakken has kept the media away from training to prepare custom set-piece variations. The Norwegian side wants to leverage Erling Haaland's physical presence in the box, and security prepares for over 6,000 traveling Swedes in Oslo.",
            "author": "UEFA News Desk",
            "readTime": "3 min",
            "tag": "Opponent scouting",
            "relatedPlayers": []
          }
        ]
      }
    }
  },
  "matchReports": {},
  "lastUpdated": "2026-05-26 @ 13:36:19 local time"
};
