// Dynamic Hub Data feed generated by real-time automated research.
// This database is automatically generated 5 times per day.

const DYNAMIC_HUB_DATA = {
  "ticker": [
    "⚽ Premier League 2025-26 season review: our predictions v reality",
    "⚽ Jon Dahl Tomasson Sweden football - Channels Television",
    "⚽ Just how good is Sweden football manager Graham Potter's Swedish? - The Local Sweden",
    "⚽ Sweden's football team discards its trainer after Kosovo loss - KosovaPress",
    "⚽ Sweden qualify for World Cup after Viktor Gyökeres hits late winner against Poland - The Guardian",
    "⚽ Haryana girls set for Sweden football tourney - The New Indian Express",
    "⚽ Zlatan Ibrahimović Says Goodbye to Swedish National Football Team in New Volvo V90 Film - PR Newswire",
    "⚽ Derby Week: Title set to be decided between rivals in Sweden's football heartland - Flashscore.com",
    "⚽ Five players retire from Swedish national football team - Anadolu Ajansı",
    "⚽ Sweden Extends Winless Potter's Contract Until 2030 World Cup - 조선일보",
    "⚽ Zlatan Ibrahimović says goodbye to Swedish national football team in new Volvo V90 film - MultiVu",
    "⚽ Sweden football team Photo Jonathan Nackstrand AFP - Cision News",
    "⚽ Sweden Euro Cup: A glorious legacy of Sweden's football team before Euro 2024 - vocal.media",
    "⚽ Sweden football legend Zlatan Ibrahimovic's statue fenced off as Malmo fans vent fury over Hammarby deal - Firstpost",
    "⚽ 'Believe in your damn self': Sweden's football team switches jersey names for inspiring quotes - SBS Australia",
    "⚽ Who are the out LGBTQ+ Swedish players confirmed to be playing in the 2025 Euros? - PinkNews",
    "⚽ England vs Sweden football head-to-head: When did Three Lions last beat Sweden, and will Zlatan Ibrahimovic play? - talkSPORT",
    "⚽ Sweden football fans in London: sweaty optimism gives way to a sad silence - The Guardian",
    "⚽ Sweden Football: Second-half goals see Sweden beat Hungary in Budapest friendly - Flashscore.com",
    "⚽ Swedish National Football Team Player Embraces Islam - Morocco World News",
    "⚽ #EFFC25 TO TAKE PLACE IN MALMÖ, SWEDEN - Football Supporters Europe -",
    "⚽ Sweden's football coach apologises after post-match row on live television - The Local Sweden",
    "⚽ New Volvo V90 marketing features Sweden’s football legend Zlatan Ibrahimovic - Luxury Lifestyle Magazine",
    "⚽ Sweden Football Star Zlatan Ibrahimovic Attacks Guardiola - Spiegel",
    "⚽ Terrorist Attack Halts Belgium-Sweden Football Match, Two Fans Killed: Report - The Quint",
    "⚽ Zlatan criticises Sweden football boss over Kulusevski snub - The Peninsula Qatar",
    "⚽ Gunman kills 2 Swedes in Brussels, prompting terror alert and halt of Belgium-Sweden football match - The Malta Independent",
    "⚽ VIDEO: Zlatan Ibrahimovic says goodbye to the Swedish national football team in new Volvo V90 film - Paul Tan",
    "⚽ Sweden's football champion joins FC Ararat-Armenia - NEWS.am Sport",
    "⚽ Yura Movsisyan joins Sweden football club - NEWS.am Sport",
    "⚽ Zlatan Ibrahimovic in Sweden training with Manchester United on horizon – in pictures - The National",
    "⚽ Kim Seung-gyu gets ready for the match against \"tall\" Sweden - Football Tribe",
    "⚽ World Cup 2018: The best Scandinavian bars showing England vs Sweden in London - London Evening Standard",
    "⚽ England vs Sweden football record: What has been the results between the teams, and is Zlatan Ibrahimovic playing at the World Cup? - The Irish Sun",
    "⚽ 15 Greatest Swedish Players in Football History [Ranked] - GiveMeSport",
    "⚽ Sweden's football player found unconscious - REASON - İdman.Biz",
    "⚽ England vs Sweden football record: What has been the results between the teams and is Zlatan Ibrahimovic playing for them at the World Cup? - The Sun",
    "⚽ Victor Lindelof stops bag robbery on holiday in Sweden - Tribuna.com",
    "⚽ Alexander Isak returns from injury to boost Liverpool and Sweden - Geo Super",
    "⚽ Spain slip to World Cup qualifier loss in Sweden - Football Espana",
    "⚽ Jordi Alba ready to lead Spain in Sergio Busquets’ absence against Sweden - Football Espana"
  ],
  "timeline": {
    "2026-05-29": {
      "1": {
        "timeLabel": "07:00",
        "name": "Breakfast Camp Report",
        "articles": [
          {
            "id": "crawled_4207_0",
            "category": "sweden",
            "type": "News",
            "title": "Premier League 2025-26 season review: our predictions v reality",
            "bullets": [
              "&lt;p&gt;We picked Liverpool as champions, Chelsea as challengers and tipped Brentford and Sunderlan...",
              "Reported live by The Guardian Football.",
              "Technical staff notes player physical and recovery markers look strong."
            ],
            "summary": "&lt;p&gt;We picked Liverpool as champions, Chelsea as challengers and tipped Brentford and Sunderland to go down. Oh dear&lt;/p&gt;&lt;p&gt;&lt;strong&gt;What we predicted: &lt;/strong&gt;Mikel Arteta vowed this would be a “big summer” after finishing as runners-up in the Premier League for a third season in succession and the new sporting director, Andrea Berta, has delivered on a number of signings in his first transfer window. The question now for Arsenal supporters is whether Martín Zubimendi, Christian Nørgaard, Noni Madueke, Viktor Gyökeres, Cristhian Mosquera and Kepa Arrizabalaga can help them take that elusive final step to becoming champions for the first time since the Invincibles in 2004.&lt;/p&gt; &lt;a href=\"https://www.theguardian.com/football/2026/may/26/premier-league-2025-26-season-review-predictions-reality-liverpool-chelsea-brentford-sunderland\"&gt;Continue reading...&lt;/a&gt;",
            "author": "The Guardian Football Editorial Team",
            "readTime": "3 min",
            "tag": "Camp Brief",
            "relatedPlayers": []
          },
          {
            "id": "crawled_4207_1",
            "category": "sweden",
            "type": "News",
            "title": "Jon Dahl Tomasson Sweden football - Channels Television",
            "bullets": [
              "&lt;a href=\"https://news.google.com/rss/articles/CBMizwFBVV95cUxPejFQU1d5Y1NpOGlJeFpydUdibm9pVTZzZDZ...",
              "Reported live by Google News Sweden.",
              "Technical staff notes player physical and recovery markers look strong."
            ],
            "summary": "&lt;a href=\"https://news.google.com/rss/articles/CBMizwFBVV95cUxPejFQU1d5Y1NpOGlJeFpydUdibm9pVTZzZDZ3R2I5Tmh0Z3AweWR3TDgxWVdEQVNOVzJOWk5hWkZYVC1Bd1Jsb2dBR3lUSlV0Y1dpa3dONUxwQXBvTVI1MlBUaGlDdng0azZnc3E3cGJTOF9TVzdhM0JxVkYzUzVwV1pSeGVIRzF4NXFTeHc4TUVHR2lTVkFSTVRwMlk5MlVVU1FiSnJ5dnl2XzNxQzNYQ0FPdWNqOVZmSmkyc1pPU2NhZHFxYW42OHotZFhqSEU?oc=5\" target=\"_blank\"&gt;Jon Dahl Tomasson Sweden football&lt;/a&gt;&amp;nbsp;&amp;nbsp;&lt;font color=\"#6f6f6f\"&gt;Channels Television&lt;/font&gt;",
            "author": "Google News Sweden Editorial Team",
            "readTime": "3 min",
            "tag": "Camp Brief",
            "relatedPlayers": []
          },
          {
            "id": "crawled_4207_2",
            "category": "sweden",
            "type": "News",
            "title": "Just how good is Sweden football manager Graham Potter's Swedish? - The Local Sweden",
            "bullets": [
              "&lt;a href=\"https://news.google.com/rss/articles/CBMiogNBVV95cUxNSXBVT0JTX2RWODVFYnRsQWZRei1Ka2lQZEZ...",
              "Reported live by Google News Sweden.",
              "Technical staff notes player physical and recovery markers look strong."
            ],
            "summary": "&lt;a href=\"https://news.google.com/rss/articles/CBMiogNBVV95cUxNSXBVT0JTX2RWODVFYnRsQWZRei1Ka2lQZEZBbFh6QXJfY3otc2oxT0dDMktIUXYxRkpaVk1OWTZhd3B3VTFrY19pdEh2SUltZUJ1OFZIMEVQLWs5Tzh5QTI3WEtaY19IZ2E0RGVjWVpqamZQcmFkOEk1Tzlqc2NwRkFqWmFNUzJaNTMtOFN5V0dtN2tUNEwxQlRtOXVxanFDWFNLSWhWQ2NMQkN4Ml82MHFscVFrTzRfT1BFTWhMZXZjYmdpT0U4WUVvQ0EtY0p6UDMtRTZHa0ZIdFU0cE42OXJ5MXFvcTBnRnR0Q0R3MjdRZDV3NGdYNzhzWVBkcTVlUmVyTUtxX3poUEVXdGp5TzhpRmVIMG05aUhlNmdQcmF0TnRJQnJVYkJqUDZrOWlVWVpJSHliU2hDSnBCLUxMWmhXcXFwS2liSUtDNEo1bmJKMVhHNkpFT0h4dXhaNG9iMTI5YXVmMnNUekszMW8wV0xNaDFGSFYxaWI0cTZFd2h3VzBtSzZzUE5KOHAwRFcycEN2TlVGU0hBLUdlNU1hVDVR?oc=5\" target=\"_blank\"&gt;Just how good is Sweden football manager Graham Potter's Swedish?&lt;/a&gt;&amp;nbsp;&amp;nbsp;&lt;font color=\"#6f6f6f\"&gt;The Local Sweden&lt;/font&gt;",
            "author": "Google News Sweden Editorial Team",
            "readTime": "3 min",
            "tag": "Camp Brief",
            "relatedPlayers": []
          },
          {
            "id": "crawled_4207_3",
            "category": "sweden",
            "type": "News",
            "title": "Sweden's football team discards its trainer after Kosovo loss - KosovaPress",
            "bullets": [
              "&lt;a href=\"https://news.google.com/rss/articles/CBMikgFBVV95cUxNVHdMMWE2WERESGMyV2Z3T1J0ZllDLVJRYnB...",
              "Reported live by Google News Sweden.",
              "Technical staff notes player physical and recovery markers look strong."
            ],
            "summary": "&lt;a href=\"https://news.google.com/rss/articles/CBMikgFBVV95cUxNVHdMMWE2WERESGMyV2Z3T1J0ZllDLVJRYnBNa3JCeVdUcmdGM3d3VXB3V3VUd2JIWGNsZTdxbTk3SV8wN1hBem5rbVBLLVlDaWk0bUZsbklhN2ZxUkRRRlNqYlQwb0RyTkk1bU0wY2JIbjU5cHh5M0U3N09XX3o4U3MyUG5YWTVwNHVfVkNfRExJQQ?oc=5\" target=\"_blank\"&gt;Sweden's football team discards its trainer after Kosovo loss&lt;/a&gt;&amp;nbsp;&amp;nbsp;&lt;font color=\"#6f6f6f\"&gt;KosovaPress&lt;/font&gt;",
            "author": "Google News Sweden Editorial Team",
            "readTime": "3 min",
            "tag": "Camp Brief",
            "relatedPlayers": []
          },
          {
            "id": "crawled_4207_4",
            "category": "sweden",
            "type": "News",
            "title": "Sweden qualify for World Cup after Viktor Gyökeres hits late winner against Poland - The Guardian",
            "bullets": [
              "&lt;a href=\"https://news.google.com/rss/articles/CBMimAFBVV95cUxPTTFlWmwyM0tCM3lzNmNudkNTMWQ2OTZyWVJ...",
              "Reported live by Google News Sweden.",
              "Technical staff notes player physical and recovery markers look strong."
            ],
            "summary": "&lt;a href=\"https://news.google.com/rss/articles/CBMimAFBVV95cUxPTTFlWmwyM0tCM3lzNmNudkNTMWQ2OTZyWVJEeUV2aTBtNWtfYnZrQlhDNVYycm53Y0RMZkI4Mk5hVUZCamR2VWxYT1R5dXFnd01uYk5UNUlFQjIxTUphY2VUWWY5QXRtanFtLVFfNm0wM2txbko4ZE9JZ2pfM2FkMjdXc0ZuZFNQeGF6eldjWmlhcGRvUTc3Mg?oc=5\" target=\"_blank\"&gt;Sweden qualify for World Cup after Viktor Gyökeres hits late winner against Poland&lt;/a&gt;&amp;nbsp;&amp;nbsp;&lt;font color=\"#6f6f6f\"&gt;The Guardian&lt;/font&gt;",
            "author": "Google News Sweden Editorial Team",
            "readTime": "3 min",
            "tag": "Camp Brief",
            "relatedPlayers": []
          },
          {
            "id": "crawled_4207_5",
            "category": "sweden",
            "type": "News",
            "title": "Haryana girls set for Sweden football tourney - The New Indian Express",
            "bullets": [
              "&lt;a href=\"https://news.google.com/rss/articles/CBMiqAFBVV95cUxOWGJTaTlvRTZjVHNWR1h6SC1tWF9GQmlqQmd...",
              "Reported live by Google News Sweden.",
              "Technical staff notes player physical and recovery markers look strong."
            ],
            "summary": "&lt;a href=\"https://news.google.com/rss/articles/CBMiqAFBVV95cUxOWGJTaTlvRTZjVHNWR1h6SC1tWF9GQmlqQmdHTjByUGJNbHBlQzZmdnY4YXhaYWVwbjJNSDg3SzlaVjRael9QNzl0ZXRvVVlZRHNwUnVHQzZzU2hNSEx4dE5GV0NxRThYaElWbk5pcTJiS0VWcjFybTVKZjU5TUtsdEMxeVRWT2RMbV9zTFN2TVdVbTBvMWpyM1psYXI3WFE1a25FTEFBT0rSAbYBQVVfeXFMUEZlZjlRajB4ZVA5ZjlYZzRkNU81T0poMDRIWGNPUk1KM3RKSlZlUDFHVnFzS1QzTEhGdWxDRk1HQmZISkJzUlVFYlhsY1pUWTNsWUxsYWVPWkNtdTIzbFpRRW5sMG8xQXBhWUtxYzRkSnlZQWhOSkxuREVud2d2WnNPQ1VzSzF3clNEbUx2LTdpNGNCd0kzVldjZmJkMEk3NEJ6YXUyajE4MGNob21TcUZ6UFNKMlE?oc=5\" target=\"_blank\"&gt;Haryana girls set for Sweden football tourney&lt;/a&gt;&amp;nbsp;&amp;nbsp;&lt;font color=\"#6f6f6f\"&gt;The New Indian Express&lt;/font&gt;",
            "author": "Google News Sweden Editorial Team",
            "readTime": "3 min",
            "tag": "Camp Brief",
            "relatedPlayers": []
          },
          {
            "id": "crawled_4207_6",
            "category": "sweden",
            "type": "News",
            "title": "Zlatan Ibrahimović Says Goodbye to Swedish National Football Team in New Volvo V90 Film - PR Newswire",
            "bullets": [
              "&lt;a href=\"https://news.google.com/rss/articles/CBMi3gFBVV95cUxNQkxNSzVCbVNMclRnU19zeGxsZ1pFWmxkb0M...",
              "Reported live by Google News Sweden.",
              "Technical staff notes player physical and recovery markers look strong."
            ],
            "summary": "&lt;a href=\"https://news.google.com/rss/articles/CBMi3gFBVV95cUxNQkxNSzVCbVNMclRnU19zeGxsZ1pFWmxkb0M1Z3JmNjRRYzBSMDhRUm9rQmxWSDBXNXhBamRVckNwWjNLWVk3N1FDVU4tNmJIaDJZLUFMeTJlb2V6azhyNU81M2ZRM0VBR1JxOUg2Z1lNdWkwN0pJUDk2S25ucF85UFBpY1lGZGxFX0x4TGczeFMweDVIY2J2cDJCeVdTaFFkenZ4RkNEa2p1NlVKZ2pUYmR6Wl9oQzhYUTN3RlBtSVgtMkR5NkFvSER2LUlFNzYtSF9zeHJmQTEtaGNWWVE?oc=5\" target=\"_blank\"&gt;Zlatan Ibrahimović Says Goodbye to Swedish National Football Team in New Volvo V90 Film&lt;/a&gt;&amp;nbsp;&amp;nbsp;&lt;font color=\"#6f6f6f\"&gt;PR Newswire&lt;/font&gt;",
            "author": "Google News Sweden Editorial Team",
            "readTime": "3 min",
            "tag": "Camp Brief",
            "relatedPlayers": []
          },
          {
            "id": "crawled_4207_7",
            "category": "sweden",
            "type": "News",
            "title": "Derby Week: Title set to be decided between rivals in Sweden's football heartland - Flashscore.com",
            "bullets": [
              "&lt;a href=\"https://news.google.com/rss/articles/CBMi2AFBVV95cUxPNDZfZUI3NW5DOTVSQ2MwQ3JMekdHNFV4Z01...",
              "Reported live by Google News Sweden.",
              "Technical staff notes player physical and recovery markers look strong."
            ],
            "summary": "&lt;a href=\"https://news.google.com/rss/articles/CBMi2AFBVV95cUxPNDZfZUI3NW5DOTVSQ2MwQ3JMekdHNFV4Z014M1A4NWlCcEpPamRSbElJTGhxRk5henBoMHdJaWpEN2d5SXpEZG5VOTVCamFWT3Nsd3c1Z2RQb3Rrdl8xQ2ZTb0dmS0g1WTVCTEZwVDdkSVpBUDlvTFA4ZG12VWxxQkhEWWJYeV8wbnJlZUtIT3VpdjBRQ0JWWWhGTTROR1dqR3NSSXUwSWtYb0p1WGpOMzB5MXFCODRObHB2NnhucmlMSUw3S2xRNlZmbjkwZ2NrdjJVUG5rY0Q?oc=5\" target=\"_blank\"&gt;Derby Week: Title set to be decided between rivals in Sweden's football heartland&lt;/a&gt;&amp;nbsp;&amp;nbsp;&lt;font color=\"#6f6f6f\"&gt;Flashscore.com&lt;/font&gt;",
            "author": "Google News Sweden Editorial Team",
            "readTime": "3 min",
            "tag": "Camp Brief",
            "relatedPlayers": []
          },
          {
            "id": "crawled_4207_8",
            "category": "sweden",
            "type": "News",
            "title": "Five players retire from Swedish national football team - Anadolu Ajansı",
            "bullets": [
              "&lt;a href=\"https://news.google.com/rss/articles/CBMimwFBVV95cUxOdDY5Z290WUszRG1xS3FaY2MyQXBIWExfZ1E...",
              "Reported live by Google News Sweden.",
              "Technical staff notes player physical and recovery markers look strong."
            ],
            "summary": "&lt;a href=\"https://news.google.com/rss/articles/CBMimwFBVV95cUxOdDY5Z290WUszRG1xS3FaY2MyQXBIWExfZ1EyVS1JTDYxdllaVnozM1EzR2tIN1B2dlJsRUZROVl2ZkNzbzBTNkdSUlZiTXpJVTFSay1TdGdzZTNtb1M1RVdRaWNaaUhjaWloWlZ4cUFyQnVWQ3hyUDJxWnVVOHJ3a0llakRTSHowWnI2UHBUT282ZTZMUjREb1NGcw?oc=5\" target=\"_blank\"&gt;Five players retire from Swedish national football team&lt;/a&gt;&amp;nbsp;&amp;nbsp;&lt;font color=\"#6f6f6f\"&gt;Anadolu Ajansı&lt;/font&gt;",
            "author": "Google News Sweden Editorial Team",
            "readTime": "3 min",
            "tag": "Camp Brief",
            "relatedPlayers": []
          },
          {
            "id": "crawled_4207_9",
            "category": "sweden",
            "type": "News",
            "title": "Sweden Extends Winless Potter's Contract Until 2030 World Cup - 조선일보",
            "bullets": [
              "&lt;a href=\"https://news.google.com/rss/articles/CBMihgFBVV95cUxQNHF3RC1zUS1DdTdobEdPT0dDdHRQbkRYTTc...",
              "Reported live by Google News Sweden.",
              "Technical staff notes player physical and recovery markers look strong."
            ],
            "summary": "&lt;a href=\"https://news.google.com/rss/articles/CBMihgFBVV95cUxQNHF3RC1zUS1DdTdobEdPT0dDdHRQbkRYTTcwcnZoenNpTnNGMy1TRi1MdGVWNFFlZVZMb1VXc3RwaGNGc1ZBVDFRN3hab1EzX201dk9FLXU0NlhybkNrbUNUTHRiMmtFWjk5YmJsc25xTWVCUjFsSk1SZHY5OTVEU1NDS3hJdw?oc=5\" target=\"_blank\"&gt;Sweden Extends Winless Potter's Contract Until 2030 World Cup&lt;/a&gt;&amp;nbsp;&amp;nbsp;&lt;font color=\"#6f6f6f\"&gt;조선일보&lt;/font&gt;",
            "author": "Google News Sweden Editorial Team",
            "readTime": "3 min",
            "tag": "Camp Brief",
            "relatedPlayers": []
          },
          {
            "id": "crawled_4207_10",
            "category": "sweden",
            "type": "News",
            "title": "Zlatan Ibrahimović says goodbye to Swedish national football team in new Volvo V90 film - MultiVu",
            "bullets": [
              "&lt;a href=\"https://news.google.com/rss/articles/CBMijAFBVV95cUxQb0JRdDZzREI3M05XMkVQSWpJNVowRnBmU09...",
              "Reported live by Google News Sweden.",
              "Technical staff notes player physical and recovery markers look strong."
            ],
            "summary": "&lt;a href=\"https://news.google.com/rss/articles/CBMijAFBVV95cUxQb0JRdDZzREI3M05XMkVQSWpJNVowRnBmU09SZmxnN3pJa01GTy03M3pMa2w4YkJTWEVoLVZtazZLcl9MLXhhMkw2c2JndUp1ZGhTUkNNbTczeUp4Y0diOVhyTTlCWW4zNklsRzdtV1B5MFRvQjNNdVlWemJBckwzMjdkNUFUTG8ya01Hag?oc=5\" target=\"_blank\"&gt;Zlatan Ibrahimović says goodbye to Swedish national football team in new Volvo V90 film&lt;/a&gt;&amp;nbsp;&amp;nbsp;&lt;font color=\"#6f6f6f\"&gt;MultiVu&lt;/font&gt;",
            "author": "Google News Sweden Editorial Team",
            "readTime": "3 min",
            "tag": "Camp Brief",
            "relatedPlayers": []
          },
          {
            "id": "crawled_4207_11",
            "category": "sweden",
            "type": "News",
            "title": "Sweden football team Photo Jonathan Nackstrand AFP - Cision News",
            "bullets": [
              "&lt;a href=\"https://news.google.com/rss/articles/CBMioAFBVV95cUxQU2NCR0JmSXRSSjdiQWxWZE1hY2VSbk5WZC0...",
              "Reported live by Google News Sweden.",
              "Technical staff notes player physical and recovery markers look strong."
            ],
            "summary": "&lt;a href=\"https://news.google.com/rss/articles/CBMioAFBVV95cUxQU2NCR0JmSXRSSjdiQWxWZE1hY2VSbk5WZC0tU29PdlFnYlE3ZWV4ekl5bzFYby1UTTJmaHJQMFpRdVZJMzItRFFPMUIzSEFOSjEwNHJmbm4yaFBSbnMycGsyU0xfZjd0QjhnV2FmNDR4MWVwLUlpazliVVowZS1DYnUtWFJyRTZOOGROck11NXRILTUwTGdVc0hwSEFISVFv?oc=5\" target=\"_blank\"&gt;Sweden football team Photo Jonathan Nackstrand AFP&lt;/a&gt;&amp;nbsp;&amp;nbsp;&lt;font color=\"#6f6f6f\"&gt;Cision News&lt;/font&gt;",
            "author": "Google News Sweden Editorial Team",
            "readTime": "3 min",
            "tag": "Camp Brief",
            "relatedPlayers": []
          },
          {
            "id": "crawled_4207_12",
            "category": "sweden",
            "type": "News",
            "title": "Sweden Euro Cup: A glorious legacy of Sweden's football team before Euro 2024 - vocal.media",
            "bullets": [
              "&lt;a href=\"https://news.google.com/rss/articles/CBMioAFBVV95cUxNTkZuZUx4N0NCdks0anlVaUIzS3hUUnAzaXN...",
              "Reported live by Google News Sweden.",
              "Technical staff notes player physical and recovery markers look strong."
            ],
            "summary": "&lt;a href=\"https://news.google.com/rss/articles/CBMioAFBVV95cUxNTkZuZUx4N0NCdks0anlVaUIzS3hUUnAzaXN6U1M3cERNdVpYcGtZa0hVb0xveHJadkxCcjI4ei1oeXY2YW1ScHRVamJaQkp1eUstZFdmYmQ5RjFVdkxzQ1pDQTEyZFVuaG00RU44ZVVXMldyZXRrR1lLQWs4bWltRE1vbnpRNktKTjlrZ0NCR1B4STFDVnJKTEtVWUJsM2tC?oc=5\" target=\"_blank\"&gt;Sweden Euro Cup: A glorious legacy of Sweden's football team before Euro 2024&lt;/a&gt;&amp;nbsp;&amp;nbsp;&lt;font color=\"#6f6f6f\"&gt;vocal.media&lt;/font&gt;",
            "author": "Google News Sweden Editorial Team",
            "readTime": "3 min",
            "tag": "Camp Brief",
            "relatedPlayers": []
          },
          {
            "id": "crawled_4207_13",
            "category": "sweden",
            "type": "News",
            "title": "Sweden football legend Zlatan Ibrahimovic's statue fenced off as Malmo fans vent fury over Hammarby deal - Firstpost",
            "bullets": [
              "&lt;a href=\"https://news.google.com/rss/articles/CBMi4wFBVV95cUxNSTZZZGRoQXdLdkl0QlVZSEpCZDM2NVNEN20...",
              "Reported live by Google News Sweden.",
              "Technical staff notes player physical and recovery markers look strong."
            ],
            "summary": "&lt;a href=\"https://news.google.com/rss/articles/CBMi4wFBVV95cUxNSTZZZGRoQXdLdkl0QlVZSEpCZDM2NVNEN202dzNLbzE1eWtOTzFnXzJFb2Z1QU9CT3FyQ3RRSGhqNTA5UWg2UGdRcTZUck9nVmREQUluUWQ2MU12RFZ6dkdRR1VUTnJIUmZXd2NnTm5WYkdjcWdDX2NubVV5Zzdac1FzS0d1YTR4eHVkMnFDbUk4Mkh0bDlDUkRNX1JKMTBBQ0IxbzgzUzNYVDV4SzZpXzFyYWhjXzktZVJaYjV1Q3Q1bmdCWVRCMTVaUHVVaXlhQ1UzQk1XVXZWUmFiYjJwWkwxd9IB6AFBVV95cUxPN2RsSGVEcnJ4cHJidEtrbVpBWDNtUTlrUVl6eEJHMjlXZW5fVnl3OUFRZzdHQ3VqNjZTWXVHZnB0SmtNMEIza3hWMHRJVHZxR1U1Q2ZQaWcwcHRocm0ydWl3eUQ3V243Y1k1M3FReXY1eHpWb0ppV0pHTzlyTlJpZnBWeEh3V2E3VENRM3QwZHNNcmRyb3pOaTUzejZPQlhLTkdHb201ZmZHNmlrNXVGUmhtWHZwODdyQ0xxN0ZFQ3phTl8wY3N1NkhwNkhSaDBHdlllYmY1dkJsRy1HRjA0MC1CZE1WUm1H?oc=5\" target=\"_blank\"&gt;Sweden football legend Zlatan Ibrahimovic's statue fenced off as Malmo fans vent fury over Hammarby deal&lt;/a&gt;&amp;nbsp;&amp;nbsp;&lt;font color=\"#6f6f6f\"&gt;Firstpost&lt;/font&gt;",
            "author": "Google News Sweden Editorial Team",
            "readTime": "3 min",
            "tag": "Camp Brief",
            "relatedPlayers": []
          },
          {
            "id": "crawled_4207_14",
            "category": "sweden",
            "type": "News",
            "title": "'Believe in your damn self': Sweden's football team switches jersey names for inspiring quotes - SBS Australia",
            "bullets": [
              "&lt;a href=\"https://news.google.com/rss/articles/CBMi0gFBVV95cUxOaGZubTBrdy1pbGhRZWVORUk4a24tbWRsZ1h...",
              "Reported live by Google News Sweden.",
              "Technical staff notes player physical and recovery markers look strong."
            ],
            "summary": "&lt;a href=\"https://news.google.com/rss/articles/CBMi0gFBVV95cUxOaGZubTBrdy1pbGhRZWVORUk4a24tbWRsZ1hpZTFPaGhjQm1RSmY2X0x6Zmpvb3c0OWFNU1J1b1lxbGVYNFBwZ2NsWGQ2Vi1CdDYzdzVVVHNJZU1qanpNNGNidDRud2VyUTJ1aXRlaGlYRDB3YkEyeGJQRU9pWHhIWldiU1p2amtJUnZRX0hQSUh5NWZhOVdla2pjcENaN3VJbU5sUHhFR2Zzc0ZmV3B6cTJ4QjdmSEtlQldfTTUyMjRyY0JzajRwNHNDRzNadFNhNEE?oc=5\" target=\"_blank\"&gt;'Believe in your damn self': Sweden's football team switches jersey names for inspiring quotes&lt;/a&gt;&amp;nbsp;&amp;nbsp;&lt;font color=\"#6f6f6f\"&gt;SBS Australia&lt;/font&gt;",
            "author": "Google News Sweden Editorial Team",
            "readTime": "3 min",
            "tag": "Camp Brief",
            "relatedPlayers": []
          },
          {
            "id": "crawled_4207_15",
            "category": "sweden",
            "type": "News",
            "title": "Who are the out LGBTQ+ Swedish players confirmed to be playing in the 2025 Euros? - PinkNews",
            "bullets": [
              "&lt;a href=\"https://news.google.com/rss/articles/CBMiiwFBVV95cUxNdExJWFRFTElsQ0tlTXRjOTNXR1U4bVZmYVJ...",
              "Reported live by Google News Sweden.",
              "Technical staff notes player physical and recovery markers look strong."
            ],
            "summary": "&lt;a href=\"https://news.google.com/rss/articles/CBMiiwFBVV95cUxNdExJWFRFTElsQ0tlTXRjOTNXR1U4bVZmYVJlWGlNemxFRUdNWTJGMzkyME82ZUtRbjBGS3FUcDB0a3MtU3o0TE5sNTg2NHl2cHhDTnF4N0hmd1lfLWs0RlJDM29xQ0hDOUNYWFJXaUhjQWF6OFJiV0VkdFdZRXA3Y0ZacGFxektMSnEw?oc=5\" target=\"_blank\"&gt;Who are the out LGBTQ+ Swedish players confirmed to be playing in the 2025 Euros?&lt;/a&gt;&amp;nbsp;&amp;nbsp;&lt;font color=\"#6f6f6f\"&gt;PinkNews&lt;/font&gt;",
            "author": "Google News Sweden Editorial Team",
            "readTime": "3 min",
            "tag": "Camp Brief",
            "relatedPlayers": []
          },
          {
            "id": "crawled_4207_16",
            "category": "sweden",
            "type": "News",
            "title": "England vs Sweden football head-to-head: When did Three Lions last beat Sweden, and will Zlatan Ibrahimovic play? - talkSPORT",
            "bullets": [
              "&lt;a href=\"https://news.google.com/rss/articles/CBMiuAFBVV95cUxPRGZ5bWo3MktyZlJ0Z0ZRUF85NFdDUkQ5cjh...",
              "Reported live by Google News Sweden.",
              "Technical staff notes player physical and recovery markers look strong."
            ],
            "summary": "&lt;a href=\"https://news.google.com/rss/articles/CBMiuAFBVV95cUxPRGZ5bWo3MktyZlJ0Z0ZRUF85NFdDUkQ5cjhoam9aT0E1b1VHRUlpR29CcTZLNWV5ZE9rbnpGNExEWGE3ZUVDbS13c2dULWJIc19jOFJuUlp5WGZ3WTNQUjNMOTlKQnp4cDhTZXd6ZGNnZzZ5WGVGWWNiY2JNcUQ4anJZZl9oV1VBZG5BLUo0TjBJZVNFbEZEdXZkSHNrU0xLT3NFV2RnZG9NNEp5enQ5RzBkVFdJQUNM?oc=5\" target=\"_blank\"&gt;England vs Sweden football head-to-head: When did Three Lions last beat Sweden, and will Zlatan Ibrahimovic play?&lt;/a&gt;&amp;nbsp;&amp;nbsp;&lt;font color=\"#6f6f6f\"&gt;talkSPORT&lt;/font&gt;",
            "author": "Google News Sweden Editorial Team",
            "readTime": "3 min",
            "tag": "Camp Brief",
            "relatedPlayers": []
          },
          {
            "id": "crawled_4207_17",
            "category": "sweden",
            "type": "News",
            "title": "Sweden football fans in London: sweaty optimism gives way to a sad silence - The Guardian",
            "bullets": [
              "&lt;a href=\"https://news.google.com/rss/articles/CBMiswFBVV95cUxQR2d1MFRDYmZ2WWZOQTU1ZzVQMjYyX1cxaGJ...",
              "Reported live by Google News Sweden.",
              "Technical staff notes player physical and recovery markers look strong."
            ],
            "summary": "&lt;a href=\"https://news.google.com/rss/articles/CBMiswFBVV95cUxQR2d1MFRDYmZ2WWZOQTU1ZzVQMjYyX1cxaGJJNjJkaG5qZGJGUmNpYnVVeDdvVFA3ZW50RzFLSlRCZ1hwN1FwbnJYVHdQQm03cEdSLTEtbmUyMnJhMGlTWXFQQmVMN0ZzaGNrMHdDUTd2bE9kcll6LVd3b2lBY0xsd3otM21lTXV1d1lVOEZmOHR2WjRIZERzeS0zbEtkTWtibmZGMWREN3h1czd4ZzhrQzUxcw?oc=5\" target=\"_blank\"&gt;Sweden football fans in London: sweaty optimism gives way to a sad silence&lt;/a&gt;&amp;nbsp;&amp;nbsp;&lt;font color=\"#6f6f6f\"&gt;The Guardian&lt;/font&gt;",
            "author": "Google News Sweden Editorial Team",
            "readTime": "3 min",
            "tag": "Camp Brief",
            "relatedPlayers": []
          },
          {
            "id": "crawled_4207_18",
            "category": "sweden",
            "type": "News",
            "title": "Sweden Football: Second-half goals see Sweden beat Hungary in Budapest friendly - Flashscore.com",
            "bullets": [
              "&lt;a href=\"https://news.google.com/rss/articles/CBMiywFBVV95cUxNZllTVjgycTZSZDhLVVhRWnA3WGdVTklUbk5...",
              "Reported live by Google News Sweden.",
              "Technical staff notes player physical and recovery markers look strong."
            ],
            "summary": "&lt;a href=\"https://news.google.com/rss/articles/CBMiywFBVV95cUxNZllTVjgycTZSZDhLVVhRWnA3WGdVTklUbk5Wb1BXMkFMQ0wzSEFNeEF6c1F6bDRvWHJkSFFPYU84NXVoanlqblAybE9mQkpYLUdRaERzS1ZVQ3Y4YzdjS0RfdVVQU1l2TnNZckhRTF8wS0lhOXFnX1pLemxiT2JlZnVvQjFPeTE2emU1SzZpc25waU5CcmV5ZEFsVmtTcXVGc2tsTkNtNXdaRDJGbWs5dGl0TXc5djZxMlJEZkI3WGpoMGFnSDFFUkRLOA?oc=5\" target=\"_blank\"&gt;Sweden Football: Second-half goals see Sweden beat Hungary in Budapest friendly&lt;/a&gt;&amp;nbsp;&amp;nbsp;&lt;font color=\"#6f6f6f\"&gt;Flashscore.com&lt;/font&gt;",
            "author": "Google News Sweden Editorial Team",
            "readTime": "3 min",
            "tag": "Camp Brief",
            "relatedPlayers": []
          },
          {
            "id": "crawled_4207_19",
            "category": "sweden",
            "type": "News",
            "title": "Swedish National Football Team Player Embraces Islam - Morocco World News",
            "bullets": [
              "&lt;a href=\"https://news.google.com/rss/articles/CBMijwFBVV95cUxPMXV4djZTYUJDbUduQ2ZKbFFCUmZMVHZKMFN...",
              "Reported live by Google News Sweden.",
              "Technical staff notes player physical and recovery markers look strong."
            ],
            "summary": "&lt;a href=\"https://news.google.com/rss/articles/CBMijwFBVV95cUxPMXV4djZTYUJDbUduQ2ZKbFFCUmZMVHZKMFNFVDJIMG5MODlBZ1FwUVhGZmx5eXFQd1h0dFU1a1FTdU94NTZPcVR1ZU0zdlY5X29tbkhvclVrYWh3ZkNYV0lxOHhreDNzcjV0NmoyV1R3ZkNBUUVpc3JrSDZiZ2FhWml1NGZBUDRBQnNBekJwbw?oc=5\" target=\"_blank\"&gt;Swedish National Football Team Player Embraces Islam&lt;/a&gt;&amp;nbsp;&amp;nbsp;&lt;font color=\"#6f6f6f\"&gt;Morocco World News&lt;/font&gt;",
            "author": "Google News Sweden Editorial Team",
            "readTime": "3 min",
            "tag": "Camp Brief",
            "relatedPlayers": []
          },
          {
            "id": "crawled_4207_20",
            "category": "sweden",
            "type": "News",
            "title": "#EFFC25 TO TAKE PLACE IN MALMÖ, SWEDEN - Football Supporters Europe -",
            "bullets": [
              "&lt;a href=\"https://news.google.com/rss/articles/CBMieEFVX3lxTE5BMnZ4bkgxUTRndTE3cjBlWjRGMXZZV2IzWlo...",
              "Reported live by Google News Sweden.",
              "Technical staff notes player physical and recovery markers look strong."
            ],
            "summary": "&lt;a href=\"https://news.google.com/rss/articles/CBMieEFVX3lxTE5BMnZ4bkgxUTRndTE3cjBlWjRGMXZZV2IzWlo5UGVrdkc0VTdBa2V6b3VmTFNUNUg2M1huYXB6dGdsZ0VhT1JKQzNGaDU4V2hjME5UcFpqbEFYdUtKcTVkVzlCbHBlZ2NMWGQtbW1icXhxVEd6cllQRw?oc=5\" target=\"_blank\"&gt;#EFFC25 TO TAKE PLACE IN MALMÖ, SWEDEN&lt;/a&gt;&amp;nbsp;&amp;nbsp;&lt;font color=\"#6f6f6f\"&gt;Football Supporters Europe -&lt;/font&gt;",
            "author": "Google News Sweden Editorial Team",
            "readTime": "3 min",
            "tag": "Camp Brief",
            "relatedPlayers": []
          },
          {
            "id": "crawled_4207_21",
            "category": "sweden",
            "type": "News",
            "title": "Sweden's football coach apologises after post-match row on live television - The Local Sweden",
            "bullets": [
              "&lt;a href=\"https://news.google.com/rss/articles/CBMirwNBVV95cUxPWFA1VTlINmJ4cDhzQW9Qbmk3cUpPM2JHakp...",
              "Reported live by Google News Sweden.",
              "Technical staff notes player physical and recovery markers look strong."
            ],
            "summary": "&lt;a href=\"https://news.google.com/rss/articles/CBMirwNBVV95cUxPWFA1VTlINmJ4cDhzQW9Qbmk3cUpPM2JHakpJbHY3RVNhZ0xhRGR3clJabFlDQ0YwQXB6a3VFMHU0R3JUdk9qMzNuS2d5b043c3laTXZlVnpkSW5zXy15V29mZGFQS1h6aDlMOF9mY3R5OFpaWE1tRFBwaGZFcUxUc3lESDUtRnkxbmc3QkdCZ1g5enJUTkRQbEdUbDl6aTV5eVU4emhXWkhTMHhoRE9ET0c2ampsOGEybUtQeGNJMHAzX3BHNnRCZ1NiWGhvcHJvbHJyWUtaRTMzdTVpMzgxRWttdHVNY3dsbzBPeHRJZUxrdEhDZ3o0QXZ0eFRuMnhpUHNSSUEzR3ZvVTdhaVFEaFRYTDczcFdIMVVqaHBzbXFhdzg4VmZuRTJCWWZkM21kdkV4V0N4cTFVTEZ5dTcyZkhBZ2h0bjNuZG81TldDekNNTmNHcXo3V29icnljRDdMMVR6SWRkRnVCR2VxRmxHeDhQYkQ5Z09GNU9Sa25RQUszRms3Sks3UXROOTJiQndIby00eGhXTG50c0NzR3YyVm1xRy1MMnIyT0I1MGdoUQ?oc=5\" target=\"_blank\"&gt;Sweden's football coach apologises after post-match row on live television&lt;/a&gt;&amp;nbsp;&amp;nbsp;&lt;font color=\"#6f6f6f\"&gt;The Local Sweden&lt;/font&gt;",
            "author": "Google News Sweden Editorial Team",
            "readTime": "3 min",
            "tag": "Camp Brief",
            "relatedPlayers": []
          },
          {
            "id": "crawled_4207_22",
            "category": "sweden",
            "type": "News",
            "title": "New Volvo V90 marketing features Sweden’s football legend Zlatan Ibrahimovic - Luxury Lifestyle Magazine",
            "bullets": [
              "&lt;a href=\"https://news.google.com/rss/articles/CBMizAFBVV95cUxPNWtueDU3a3BMcnh4TmlfVjRhOXc4NEsxNHV...",
              "Reported live by Google News Sweden.",
              "Technical staff notes player physical and recovery markers look strong."
            ],
            "summary": "&lt;a href=\"https://news.google.com/rss/articles/CBMizAFBVV95cUxPNWtueDU3a3BMcnh4TmlfVjRhOXc4NEsxNHVIZXVUR1pfNXg3SVV6ZU9Lai01aWRBbnRMSG5RT0lDamU1dTJXZy16S0luR19nZUZKemQxYWpERWtVQXphTWUxNGwtZW5KcDlGaFg1MVhKMXlQcDQzYkVnMldmRkg4dlVyUnlqMEljbzRPUXFiWGRpVjJ6MEVNOEpIanc3cGVhUTJYVUdfSjBLZHkxWE5DRkZtSjVHNnNQN2M1NXdZd2haVHk5SmFkWTVjZjU?oc=5\" target=\"_blank\"&gt;New Volvo V90 marketing features Sweden’s football legend Zlatan Ibrahimovic&lt;/a&gt;&amp;nbsp;&amp;nbsp;&lt;font color=\"#6f6f6f\"&gt;Luxury Lifestyle Magazine&lt;/font&gt;",
            "author": "Google News Sweden Editorial Team",
            "readTime": "3 min",
            "tag": "Camp Brief",
            "relatedPlayers": []
          },
          {
            "id": "crawled_4207_23",
            "category": "sweden",
            "type": "News",
            "title": "Sweden Football Star Zlatan Ibrahimovic Attacks Guardiola - Spiegel",
            "bullets": [
              "&lt;a href=\"https://news.google.com/rss/articles/CBMiugFBVV95cUxQQ0p4N1VPa2NVMG1VamlWQkdTTlhpM2I4ZEN...",
              "Reported live by Google News Sweden.",
              "Technical staff notes player physical and recovery markers look strong."
            ],
            "summary": "&lt;a href=\"https://news.google.com/rss/articles/CBMiugFBVV95cUxQQ0p4N1VPa2NVMG1VamlWQkdTTlhpM2I4ZENOLWpQdDZndzdyX3BkQlhQS2ljS3RUYklJbWdJMUlGZUhTbm9xdl9tc2J6anQ3ZzZMLWxWYklXdWlFTXBOZ2l6UlZOd20tcHZfOFZJckd0QUs3ZjZXQ1Jzb2FKcXNPbm9MU0tYNEFybXJRMm9sVndmcmdXX004UW5GMWF2MS1aNmlzTkZtUkt0R0tvQWZNU2x3djh4bDdZOEE?oc=5\" target=\"_blank\"&gt;Sweden Football Star Zlatan Ibrahimovic Attacks Guardiola&lt;/a&gt;&amp;nbsp;&amp;nbsp;&lt;font color=\"#6f6f6f\"&gt;Spiegel&lt;/font&gt;",
            "author": "Google News Sweden Editorial Team",
            "readTime": "3 min",
            "tag": "Camp Brief",
            "relatedPlayers": []
          },
          {
            "id": "crawled_4207_24",
            "category": "sweden",
            "type": "News",
            "title": "Terrorist Attack Halts Belgium-Sweden Football Match, Two Fans Killed: Report - The Quint",
            "bullets": [
              "&lt;a href=\"https://news.google.com/rss/articles/CBMinAFBVV95cUxQRTdBS2VVWEJnZVRsV2doVmJab0Nsczk0THN...",
              "Reported live by Google News Sweden.",
              "Technical staff notes player physical and recovery markers look strong."
            ],
            "summary": "&lt;a href=\"https://news.google.com/rss/articles/CBMinAFBVV95cUxQRTdBS2VVWEJnZVRsV2doVmJab0Nsczk0THNwOGlkUmNTQWtRMUctSlpUZXpVWUZwSzFyNEJyTGRMRDVUZXNUR0l5OTlFOVpfYi14cjlwdW5RU1hyb0p0MkpmdWNHYWNuTTJyQnktR2pFRlY5X2Z0TlR0OGM0Zk1LMkJ3c1lINWZscEQyT0pNSDBQZGtYX2g0MW82RFHSAaoBQVVfeXFMUEZOaDNYSnlkc1FydjVaZ2FFWWFiRzk5WGtEbm52MHJjTmNWYzBqZUJRZWZkY29veXh2T0NycnNhaEtDMWktOUxOQmlNUkJLa2ctVlQtQ1FtQ1lOZXFUUHQwcXZmLS1BaWVNTG8xUU1MQklfdlE3R0FHOXg0cEd5S3BrcVNkNHF0ZWhIUTN5OVZIOXZTTW51R0lfSmVwUjN5Nko2TDViTWxIQ1E?oc=5\" target=\"_blank\"&gt;Terrorist Attack Halts Belgium-Sweden Football Match, Two Fans Killed: Report&lt;/a&gt;&amp;nbsp;&amp;nbsp;&lt;font color=\"#6f6f6f\"&gt;The Quint&lt;/font&gt;",
            "author": "Google News Sweden Editorial Team",
            "readTime": "3 min",
            "tag": "Camp Brief",
            "relatedPlayers": []
          },
          {
            "id": "crawled_4207_25",
            "category": "sweden",
            "type": "News",
            "title": "Zlatan criticises Sweden football boss over Kulusevski snub - The Peninsula Qatar",
            "bullets": [
              "&lt;a href=\"https://news.google.com/rss/articles/CBMirAFBVV95cUxNQ1VJbks4X0V1WUxON1dkckNZWnJiMGJZbEM...",
              "Reported live by Google News Sweden.",
              "Technical staff notes player physical and recovery markers look strong."
            ],
            "summary": "&lt;a href=\"https://news.google.com/rss/articles/CBMirAFBVV95cUxNQ1VJbks4X0V1WUxON1dkckNZWnJiMGJZbEMxcVE0elJzbGg0QmpSbGlvZUhxWkRPb3ZmdGE4bm44S0t0ZXNUaVV0UF96V2V1YUtTa3htTmxRMHRkM1U4WjU2dVk1ZHJTemE0SkZrZHRpbGJBU1Q0NUNreG40T2JxNjdzNVVRMjVmQlE0NkRFeXJEZWpkTjBYODVsV01qMjJLbHBwR25OOTZWQkVO?oc=5\" target=\"_blank\"&gt;Zlatan criticises Sweden football boss over Kulusevski snub&lt;/a&gt;&amp;nbsp;&amp;nbsp;&lt;font color=\"#6f6f6f\"&gt;The Peninsula Qatar&lt;/font&gt;",
            "author": "Google News Sweden Editorial Team",
            "readTime": "3 min",
            "tag": "Camp Brief",
            "relatedPlayers": []
          },
          {
            "id": "crawled_4207_26",
            "category": "sweden",
            "type": "News",
            "title": "Gunman kills 2 Swedes in Brussels, prompting terror alert and halt of Belgium-Sweden football match - The Malta Independent",
            "bullets": [
              "&lt;a href=\"https://news.google.com/rss/articles/CBMi_gFBVV95cUxNWjJZYWgzRU9aWXBpemVwdUQ3X3cyQ1BJZzd...",
              "Reported live by Google News Sweden.",
              "Technical staff notes player physical and recovery markers look strong."
            ],
            "summary": "&lt;a href=\"https://news.google.com/rss/articles/CBMi_gFBVV95cUxNWjJZYWgzRU9aWXBpemVwdUQ3X3cyQ1BJZzdrd0hCSTZmeF9WdnNzeFdsdDZaQlRxOWFuYXRjNWJhZDZWdWJxVGxZT21rREY3V0NvbWkzblFqcXU3SVZPalBpS3VnZ2JZR1g3VjllcEpra3NWU1laTHdEZDBWdjNxdjBCSlFfMEdHWUQ5THdPT3F3cUZqSFgwd25rMVphcHRicnhuNkE2cHRRZEgyX2h4V0ZnNGs3ME1YbmtLczl0SkRMRUtRMFVteHJwM3AxWUNDQndMT1pKVWJtVmZUWnlVNEx5MVBxSXlTY0pzOTlXaGxDaFVsZUVTaUpqbENGUQ?oc=5\" target=\"_blank\"&gt;Gunman kills 2 Swedes in Brussels, prompting terror alert and halt of Belgium-Sweden football match&lt;/a&gt;&amp;nbsp;&amp;nbsp;&lt;font color=\"#6f6f6f\"&gt;The Malta Independent&lt;/font&gt;",
            "author": "Google News Sweden Editorial Team",
            "readTime": "3 min",
            "tag": "Camp Brief",
            "relatedPlayers": []
          },
          {
            "id": "crawled_4207_27",
            "category": "sweden",
            "type": "News",
            "title": "VIDEO: Zlatan Ibrahimovic says goodbye to the Swedish national football team in new Volvo V90 film - Paul Tan",
            "bullets": [
              "&lt;a href=\"https://news.google.com/rss/articles/CBMipwFBVV95cUxQWC02c3oyREl3ZWlvTXowRUV0eFB5M3Y5QzN...",
              "Reported live by Google News Sweden.",
              "Technical staff notes player physical and recovery markers look strong."
            ],
            "summary": "&lt;a href=\"https://news.google.com/rss/articles/CBMipwFBVV95cUxQWC02c3oyREl3ZWlvTXowRUV0eFB5M3Y5QzNqVnpCOFJwTnN0MFJrLWIwMzExbEFSZ3I1cDlhaTdaMUFUc01zU0JIN09KS0pjOXRrbmZ4SURTLXM1VlNVY2NENmlzeFgtc1p5cTg2TjZXT3Z0eTh3eHpQNHRmeWw3UXBtaXppalpKaXREZTJsQURieGtZNUt2aFJwOUY3WWFLdS00d2J3SQ?oc=5\" target=\"_blank\"&gt;VIDEO: Zlatan Ibrahimovic says goodbye to the Swedish national football team in new Volvo V90 film&lt;/a&gt;&amp;nbsp;&amp;nbsp;&lt;font color=\"#6f6f6f\"&gt;Paul Tan&lt;/font&gt;",
            "author": "Google News Sweden Editorial Team",
            "readTime": "3 min",
            "tag": "Camp Brief",
            "relatedPlayers": []
          },
          {
            "id": "crawled_4207_28",
            "category": "sweden",
            "type": "News",
            "title": "Sweden's football champion joins FC Ararat-Armenia - NEWS.am Sport",
            "bullets": [
              "&lt;a href=\"https://news.google.com/rss/articles/CBMilwFBVV95cUxNMFZLTUZwa0tIdzVrZEc4cWlhUnBxTVAyWXg...",
              "Reported live by Google News Sweden.",
              "Technical staff notes player physical and recovery markers look strong."
            ],
            "summary": "&lt;a href=\"https://news.google.com/rss/articles/CBMilwFBVV95cUxNMFZLTUZwa0tIdzVrZEc4cWlhUnBxTVAyWXg0VzVMSUd6WHA3aDhVelkwZWVEQTIzRmhPLUdrbUNSQ2tlYmotal9hSFpyLTl6OTZva183b0Y5VFdPUElfOXlvbUdIbVRpdFJYdUZHQU54bFRsRjFFcVFkMXBQV3ljY1pBWnZxeHJ0X0tGOE9iX3hqTDItTkRN?oc=5\" target=\"_blank\"&gt;Sweden's football champion joins FC Ararat-Armenia&lt;/a&gt;&amp;nbsp;&amp;nbsp;&lt;font color=\"#6f6f6f\"&gt;NEWS.am Sport&lt;/font&gt;",
            "author": "Google News Sweden Editorial Team",
            "readTime": "3 min",
            "tag": "Camp Brief",
            "relatedPlayers": []
          },
          {
            "id": "crawled_4207_29",
            "category": "sweden",
            "type": "News",
            "title": "Yura Movsisyan joins Sweden football club - NEWS.am Sport",
            "bullets": [
              "&lt;a href=\"https://news.google.com/rss/articles/CBMi4gFBVV95cUxPWFNrSlNLSDZEaUR3SnBsdTZEYUVOd1hGZ0N...",
              "Reported live by Google News Sweden.",
              "Technical staff notes player physical and recovery markers look strong."
            ],
            "summary": "&lt;a href=\"https://news.google.com/rss/articles/CBMi4gFBVV95cUxPWFNrSlNLSDZEaUR3SnBsdTZEYUVOd1hGZ0NvRmtSVmdMaXg2RUdKWWpMeWp4YjUxRUE0MEEwY2ROZmJyWkQ1TnRWSmNsOFZGVmZZTmZraFdCRzhBN00yWURmYVRmV0d5R3V2d1JwZlNUcWd3d2Ywb0Iwc3duTkVzM0xud3V1U2pSNHJqZmNXZVhMdkFLNkNHUHFRZHBKckhGRzVDRVg3dENWajhDTEg4U042MXBjeFRnRmhCalZpU1VlMjZNWUNqcFlMYldWTDI2Ym9YU2Zxc0x2Vi1UeHhyTGpn?oc=5\" target=\"_blank\"&gt;Yura Movsisyan joins Sweden football club&lt;/a&gt;&amp;nbsp;&amp;nbsp;&lt;font color=\"#6f6f6f\"&gt;NEWS.am Sport&lt;/font&gt;",
            "author": "Google News Sweden Editorial Team",
            "readTime": "3 min",
            "tag": "Camp Brief",
            "relatedPlayers": []
          },
          {
            "id": "crawled_4207_30",
            "category": "sweden",
            "type": "News",
            "title": "Zlatan Ibrahimovic in Sweden training with Manchester United on horizon – in pictures - The National",
            "bullets": [
              "&lt;a href=\"https://news.google.com/rss/articles/CBMixgFBVV95cUxPS2MtTDRPRVBmcmlPM1hHdVZkSjJVVkxrb2N...",
              "Reported live by Google News Sweden.",
              "Technical staff notes player physical and recovery markers look strong."
            ],
            "summary": "&lt;a href=\"https://news.google.com/rss/articles/CBMixgFBVV95cUxPS2MtTDRPRVBmcmlPM1hHdVZkSjJVVkxrb2NBU2QwS1lHbmtIaGpJVzdlN01IZXdwdkhtVlJXLWxoVWswSVVRWGlzUU1jTDF3RzVuazNLdXlhQmE5NU9tOXA1eVBnWGJTMjQ0UEE2R1NBbXhFbHFwNTJSOUhCeFBKTng2Y2pBUW1Ga3FYbkJBY0d5ck5hMzRJZ1dQRk96dWlVQkRZN0huVnFGMGlzV1lCb0tGSHpBT2hmWjcwTUtzWk4yQ2NJbUE?oc=5\" target=\"_blank\"&gt;Zlatan Ibrahimovic in Sweden training with Manchester United on horizon – in pictures&lt;/a&gt;&amp;nbsp;&amp;nbsp;&lt;font color=\"#6f6f6f\"&gt;The National&lt;/font&gt;",
            "author": "Google News Sweden Editorial Team",
            "readTime": "3 min",
            "tag": "Camp Brief",
            "relatedPlayers": []
          },
          {
            "id": "crawled_4207_31",
            "category": "sweden",
            "type": "News",
            "title": "Kim Seung-gyu gets ready for the match against \"tall\" Sweden - Football Tribe",
            "bullets": [
              "&lt;a href=\"https://news.google.com/rss/articles/CBMipAFBVV95cUxONXVQcTV1UHNKbEp1NUZFYVNMUTVDV293R3B...",
              "Reported live by Google News Sweden.",
              "Technical staff notes player physical and recovery markers look strong."
            ],
            "summary": "&lt;a href=\"https://news.google.com/rss/articles/CBMipAFBVV95cUxONXVQcTV1UHNKbEp1NUZFYVNMUTVDV293R3BrQzNEY2ZJNFVPNVdTWjFXN01OWGxhU29fNVBNUHdWbmNxTU4xdEk2VHd2QlNicEpnYWUzMk1HN3ByLXVsVWo5TlBYUXBoT3plNEdzMXZuX0REY2U0Q2dzZzFPelF0T2J4VE5ITzhXUlRvRTI2eV8tOWhuZ0VLUXhZVlp1QU1QMGt5MA?oc=5\" target=\"_blank\"&gt;Kim Seung-gyu gets ready for the match against \"tall\" Sweden&lt;/a&gt;&amp;nbsp;&amp;nbsp;&lt;font color=\"#6f6f6f\"&gt;Football Tribe&lt;/font&gt;",
            "author": "Google News Sweden Editorial Team",
            "readTime": "3 min",
            "tag": "Camp Brief",
            "relatedPlayers": []
          },
          {
            "id": "crawled_4207_32",
            "category": "sweden",
            "type": "News",
            "title": "World Cup 2018: The best Scandinavian bars showing England vs Sweden in London - London Evening Standard",
            "bullets": [
              "&lt;a href=\"https://news.google.com/rss/articles/CBMizgFBVV95cUxQcThLRTczd0pTTnlFbDJTMzJQWFZmYkowNVl...",
              "Reported live by Google News Sweden.",
              "Technical staff notes player physical and recovery markers look strong."
            ],
            "summary": "&lt;a href=\"https://news.google.com/rss/articles/CBMizgFBVV95cUxQcThLRTczd0pTTnlFbDJTMzJQWFZmYkowNVlOcGNEMTVCS2pDVl9hMGRkaTBCT2ZyVVdPQVhDcnppTW5PV1lrLWhXMXdtNF9udHM5clFzSkJwN2FrdkxqNTNnazJhRVZ4THpvTEE5M2tteXJwc1VwVGtRbm41czdaOFFQR1NKZ1g2RGlUaFRGOEJmZFBGRVgzb3dZNk0zUDdmX0kzT1NIdlBEaXZSTzgwQWw1bWtpblVqY2pRb0FyT0dqTExfNHU1aFItNmdwZw?oc=5\" target=\"_blank\"&gt;World Cup 2018: The best Scandinavian bars showing England vs Sweden in London&lt;/a&gt;&amp;nbsp;&amp;nbsp;&lt;font color=\"#6f6f6f\"&gt;London Evening Standard&lt;/font&gt;",
            "author": "Google News Sweden Editorial Team",
            "readTime": "3 min",
            "tag": "Camp Brief",
            "relatedPlayers": []
          },
          {
            "id": "crawled_4207_33",
            "category": "sweden",
            "type": "News",
            "title": "England vs Sweden football record: What has been the results between the teams, and is Zlatan Ibrahimovic playing at the World Cup? - The Irish Sun",
            "bullets": [
              "&lt;a href=\"https://news.google.com/rss/articles/CBMi-AFBVV95cUxQWU1idElUTlUwMUc4T1E0eE94bnNjV1pfZkt...",
              "Reported live by Google News Sweden.",
              "Technical staff notes player physical and recovery markers look strong."
            ],
            "summary": "&lt;a href=\"https://news.google.com/rss/articles/CBMi-AFBVV95cUxQWU1idElUTlUwMUc4T1E0eE94bnNjV1pfZktMaVh1ZnM1NHhVYkFfeUxDUzhOZlJCa3V5ODRWRW40aTNHdmF1UjJNVG5Dc1Y5UmVFMWJwcUtOVnRhYnZLTm03ZDlxeEIyRExxbXNheEdRM0VCMVdaclZpYjNUQnpicTdRT1RoVW92ZzhGcXBVQmJqM0NTUzI2QjF0dkFiQk1YNXBvdWFRUE1XMUpva000SE9jMjVQcTBpR1k5NjRQYUhRYUVyRWZ0TEZHX1doUVhWYkZmcWZScjFlbmNwX1FDdVFoNnhpRGV5VjNDdUFyTkxUNEpsZ2ZMVw?oc=5\" target=\"_blank\"&gt;England vs Sweden football record: What has been the results between the teams, and is Zlatan Ibrahimovic playing at the World Cup?&lt;/a&gt;&amp;nbsp;&amp;nbsp;&lt;font color=\"#6f6f6f\"&gt;The Irish Sun&lt;/font&gt;",
            "author": "Google News Sweden Editorial Team",
            "readTime": "3 min",
            "tag": "Camp Brief",
            "relatedPlayers": []
          },
          {
            "id": "crawled_4207_34",
            "category": "sweden",
            "type": "News",
            "title": "15 Greatest Swedish Players in Football History [Ranked] - GiveMeSport",
            "bullets": [
              "&lt;a href=\"https://news.google.com/rss/articles/CBMihwFBVV95cUxPLThHYkg5ZXVraWlQaDJ0c3pQWlVZeEo4bl9...",
              "Reported live by Google News Sweden.",
              "Technical staff notes player physical and recovery markers look strong."
            ],
            "summary": "&lt;a href=\"https://news.google.com/rss/articles/CBMihwFBVV95cUxPLThHYkg5ZXVraWlQaDJ0c3pQWlVZeEo4bl9YUTlfcDFzbGZrUkZMRllSMEM1bllwTWFCNmNfUFk0bzFKSllJTkZTTTIwLXpETVdJdUpudDUwdzV6bTJYb3BqSGxuZ3U1VHVDeGNzMDY0OEJqZHNtMS1WYUc4UGdzOTNvMFFqYXc?oc=5\" target=\"_blank\"&gt;15 Greatest Swedish Players in Football History [Ranked]&lt;/a&gt;&amp;nbsp;&amp;nbsp;&lt;font color=\"#6f6f6f\"&gt;GiveMeSport&lt;/font&gt;",
            "author": "Google News Sweden Editorial Team",
            "readTime": "3 min",
            "tag": "Camp Brief",
            "relatedPlayers": []
          },
          {
            "id": "crawled_4207_35",
            "category": "sweden",
            "type": "News",
            "title": "Sweden's football player found unconscious - REASON - İdman.Biz",
            "bullets": [
              "&lt;a href=\"https://news.google.com/rss/articles/CBMiX0FVX3lxTE9FemZYT0Z0WXlhN25oelprbTBDSC1admIxTkY...",
              "Reported live by Google News Sweden.",
              "Technical staff notes player physical and recovery markers look strong."
            ],
            "summary": "&lt;a href=\"https://news.google.com/rss/articles/CBMiX0FVX3lxTE9FemZYT0Z0WXlhN25oelprbTBDSC1admIxTkYwTzlfSlJWd0tEQVpaRmQ1blNKU194a2ZtZks3d0lBNzdWS1I3YUpUQzRVMTB0cDJzSi1qeVdvMHZLSGpj?oc=5\" target=\"_blank\"&gt;Sweden's football player found unconscious - REASON&lt;/a&gt;&amp;nbsp;&amp;nbsp;&lt;font color=\"#6f6f6f\"&gt;İdman.Biz&lt;/font&gt;",
            "author": "Google News Sweden Editorial Team",
            "readTime": "3 min",
            "tag": "Camp Brief",
            "relatedPlayers": []
          },
          {
            "id": "crawled_4207_36",
            "category": "sweden",
            "type": "News",
            "title": "England vs Sweden football record: What has been the results between the teams and is Zlatan Ibrahimovic playing for them at the World Cup? - The Sun",
            "bullets": [
              "&lt;a href=\"https://news.google.com/rss/articles/CBMizAFBVV95cUxQamZKWTZmNEJWa25ReFdfMzV1dEVtMUVIaGF...",
              "Reported live by Google News Sweden.",
              "Technical staff notes player physical and recovery markers look strong."
            ],
            "summary": "&lt;a href=\"https://news.google.com/rss/articles/CBMizAFBVV95cUxQamZKWTZmNEJWa25ReFdfMzV1dEVtMUVIaGFsdjhFbC1lRTJwQWNZckdqZ1Zwd21FTUJ5cVptX2JMNWNYMFFtZ251cTBFMTRvZldKTENtYlptd2xpRlZLeEJ4UG9PWFlaSHZpM0xNWWxYYUFjNkQxWlgySHl0RjZEdGY1REt3bThYMVRTMm1vSWlQUWZ2NENIc19HakY4ZjBuX240bWx6SDdNLXlYZk5zZGtpLVhRd2x0N0ZqUGhGVV9UZnRPM1VmcnBUZGc?oc=5\" target=\"_blank\"&gt;England vs Sweden football record: What has been the results between the teams and is Zlatan Ibrahimovic playing for them at the World Cup?&lt;/a&gt;&amp;nbsp;&amp;nbsp;&lt;font color=\"#6f6f6f\"&gt;The Sun&lt;/font&gt;",
            "author": "Google News Sweden Editorial Team",
            "readTime": "3 min",
            "tag": "Camp Brief",
            "relatedPlayers": []
          },
          {
            "id": "crawled_4207_37",
            "category": "sweden",
            "type": "News",
            "title": "Victor Lindelof stops bag robbery on holiday in Sweden - Tribuna.com",
            "bullets": [
              "&lt;a href=\"https://news.google.com/rss/articles/CBMiowFBVV95cUxQNE8wdzdURHhBSWdvTGV3eFpnSVJLOTRDXzF...",
              "Reported live by Google News Sweden.",
              "Technical staff notes player physical and recovery markers look strong."
            ],
            "summary": "&lt;a href=\"https://news.google.com/rss/articles/CBMiowFBVV95cUxQNE8wdzdURHhBSWdvTGV3eFpnSVJLOTRDXzFSUzlESF94N1I4cFJGQ0xHRHR5MzRUSEpDY09MdUZvVG1TQVhLMXNHQVhYNGN1NUs0X01NOF9Ea1IyYVRfcUw3S1dGNnhudWVTUDg1Y0E2TEZPdWhWQS1rajloRUdvTXBhVlhRLTl0TjFZSllyQ3pMOHZuODFkUUNRem1GOWQ2cHFn0gGoAUFVX3lxTE1JY1RSbm5CY0lFTXBGVjQ3Yk1seS04UTVsVXJfQlZMN2R1VllRSVRqSVFGazBnZHg2Tm1GMG9tdWFZV1VEcmhhNEd0YmxXcExKQlplYnY5cjA1elk5RnFNQS1ESGdCOWRJaEN5TUZNNnJHSDFwWUMtZ2h1Mnl5dHRQUnZmXzR5b2J3ZVd1UzFUa1pna0tKZms3WmhtdGE0NTZ0MVhUS3ZDQw?oc=5\" target=\"_blank\"&gt;Victor Lindelof stops bag robbery on holiday in Sweden&lt;/a&gt;&amp;nbsp;&amp;nbsp;&lt;font color=\"#6f6f6f\"&gt;Tribuna.com&lt;/font&gt;",
            "author": "Google News Sweden Editorial Team",
            "readTime": "3 min",
            "tag": "Camp Brief",
            "relatedPlayers": []
          },
          {
            "id": "crawled_4207_38",
            "category": "sweden",
            "type": "News",
            "title": "Alexander Isak returns from injury to boost Liverpool and Sweden - Geo Super",
            "bullets": [
              "&lt;a href=\"https://news.google.com/rss/articles/CBMilgFBVV95cUxPZmgwNjVEZEJieHdhWUdTMmRDUTE1eUdRYy1...",
              "Reported live by Google News Sweden.",
              "Technical staff notes player physical and recovery markers look strong."
            ],
            "summary": "&lt;a href=\"https://news.google.com/rss/articles/CBMilgFBVV95cUxPZmgwNjVEZEJieHdhWUdTMmRDUTE1eUdRYy10NTBld1REcnF4OUNGa0kzQ2s0XzNLckpBZXRSd2ttb2hxTVNQUWgzYWRlSmUwUm1jXzFFVVlqLUQtTzc3TVdhM0lFWE5EcEVQUmZPbi1taVFpSm5zMnBDa0hSLWtlaktRQWoyV0EtUl8wSk9mUGlvNUM3dnfSAZIBQVVfeXFMTlpSQTNLYl9QaGRjNGRDX1FOS25uVnZWMUtNM1FHR2s3ZmMyLWVsZnRFU3dDaEUxVXZOV0JObDgwMFpndnNyTTZOS054VUtDR0FSZVA2ek51NndfMVVuWHJvcjRVWkZ0Q1BvVjA5Y0NUN2Vhd1ZlOWVnMDFBTk5BTjJiNjdlOFdsajc1alFMM0pZblE?oc=5\" target=\"_blank\"&gt;Alexander Isak returns from injury to boost Liverpool and Sweden&lt;/a&gt;&amp;nbsp;&amp;nbsp;&lt;font color=\"#6f6f6f\"&gt;Geo Super&lt;/font&gt;",
            "author": "Google News Sweden Editorial Team",
            "readTime": "3 min",
            "tag": "Camp Brief",
            "relatedPlayers": []
          },
          {
            "id": "crawled_4207_39",
            "category": "sweden",
            "type": "News",
            "title": "Spain slip to World Cup qualifier loss in Sweden - Football Espana",
            "bullets": [
              "&lt;a href=\"https://news.google.com/rss/articles/CBMilgFBVV95cUxPdGowNURQODhPaHBXQVlVWnNfYUNtQkFrQnJ...",
              "Reported live by Google News Sweden.",
              "Technical staff notes player physical and recovery markers look strong."
            ],
            "summary": "&lt;a href=\"https://news.google.com/rss/articles/CBMilgFBVV95cUxPdGowNURQODhPaHBXQVlVWnNfYUNtQkFrQnJ0VGY1YlROT1BQdWJSaHBrV3d5NndjbVBFMVdQWWctZ0c4X2VPMTE2MVk3QU5IclR5c0VGMkh5aTY5WDRMSlJ2dlhWMXhDUWRVcnJ6YURrYXd4MFV1WGN0Vzd0Njg4RHNiam9EOG5JSDhnVzJnMTVTX3JiTFHSAZsBQVVfeXFMT2VkODNmcjBKTFdsemlXXzU0Z0huY0NxdGZqT0RmSGh4b2NlTXFhWmtyTDhKZXU1S2xGZlJIQzFVWG92alFFS2ZSQXJCNDlvOGhBeldSbC16TDlTbFFXZTg5Q2szUkltb2hkaFJQWjF1UmhRMk1CdW9FM09VdlpvZ3ZWVjJSdDBzUnl3ZjFPdzdwSGoxcmZkN0lhdHc?oc=5\" target=\"_blank\"&gt;Spain slip to World Cup qualifier loss in Sweden&lt;/a&gt;&amp;nbsp;&amp;nbsp;&lt;font color=\"#6f6f6f\"&gt;Football Espana&lt;/font&gt;",
            "author": "Google News Sweden Editorial Team",
            "readTime": "3 min",
            "tag": "Camp Brief",
            "relatedPlayers": []
          },
          {
            "id": "crawled_4207_40",
            "category": "sweden",
            "type": "News",
            "title": "Jordi Alba ready to lead Spain in Sergio Busquets’ absence against Sweden - Football Espana",
            "bullets": [
              "&lt;a href=\"https://news.google.com/rss/articles/CBMitgFBVV95cUxPQWN0MGhnVFVPbEJWVDFKVlROOE9Gakd1UWF...",
              "Reported live by Google News Sweden.",
              "Technical staff notes player physical and recovery markers look strong."
            ],
            "summary": "&lt;a href=\"https://news.google.com/rss/articles/CBMitgFBVV95cUxPQWN0MGhnVFVPbEJWVDFKVlROOE9Gakd1UWFrRkw1bFFjUFI5NEF2Wmp2V09IUkMtNUNzTjlZcGdfeTE3am1odnI3S3RidzIteGc1dlBOLXFQWXJlTXh5dzh0bzVieWhyRnNJS09yNEFZVndyZDYxVnBJem1JUk80akpFVC1wRlZwcXNvaXp2YlJ0Qk5EOEJ4Zl9vNll2UGdkcEVnbk5xU3RYeU9pVk16UEdkMm5NQdIBuwFBVV95cUxQbVlUTWM2Q2gtdmU4TktxdHVGWVZOMlJ6MVFqaDlYTzEtVDNlamRWNjR5ZXNWczc4Mk5WX3RMbkQ1R1pQeGVBV1VrWU5mZndyUGhQMHlEeF9qOEdMRlZ6RDdGMGFyZXBPOEhDekUxNFR5emt0ZkIyWEo3dzEtRkFKdW9KSzJmNkFWSGdSczRjOGZWeXpJSlpYR0hlMWRLbHpyNG5aUHFRajJsZkMyU1FlZDFsaXI2cU9DX1M4?oc=5\" target=\"_blank\"&gt;Jordi Alba ready to lead Spain in Sergio Busquets’ absence against Sweden&lt;/a&gt;&amp;nbsp;&amp;nbsp;&lt;font color=\"#6f6f6f\"&gt;Football Espana&lt;/font&gt;",
            "author": "Google News Sweden Editorial Team",
            "readTime": "3 min",
            "tag": "Camp Brief",
            "relatedPlayers": []
          }
        ]
      }
    }
  },
  "matchReports": {},
  "lastUpdated": "2026-05-29 @ 09:42:07 EDT"
};
