#!/usr/bin/env python3
"""
One-shot cleanup script: strips &nbsp; entities and source attributions
from all fields in data.js, copies to dist/data.js.
"""
import os
import re
import json
import shutil

WORKSPACE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA_JS = os.path.join(WORKSPACE, "data.js")
DIST_DATA_JS = os.path.join(WORKSPACE, "dist", "data.js")


def clean_text(text):
    """Replace literal &nbsp; entities, \xa0 chars, collapse double-spaces,
    and strip source attribution suffixes (text after double-space)."""
    if not isinstance(text, str):
        return text
    # Decode literal &nbsp; HTML entities
    text = text.replace('&nbsp;', ' ')
    # Replace \xa0 (non-breaking space) with regular space
    text = text.replace('\xa0', ' ')
    # Collapse runs of 2+ spaces into one
    text = re.sub(r' {2,}', ' ', text)
    return text.strip()


def clean_text_strip_attribution(text):
    """Like clean_text, but also removes source attribution after double-space.
    Google News descriptions look like 'Title  SourceName' — we strip SourceName."""
    if not isinstance(text, str):
        return text
    # First replace literal &nbsp; and \xa0
    text = text.replace('&nbsp;', ' ')
    text = text.replace('\xa0', ' ')
    # Remove everything after the first run of 2+ spaces (source attribution)
    text = re.sub(r' {2,}.*$', '', text)
    return text.strip()


def clean_article(article):
    """Clean all text fields in a single article object."""
    if 'title' in article:
        article['title'] = clean_text(article['title'])

    if 'summary' in article:
        article['summary'] = clean_text_strip_attribution(article['summary'])

    if 'fullText' in article:
        # For fullText, clean nbsp but preserve legitimate paragraph breaks
        ft = article['fullText']
        ft = ft.replace('&nbsp;', ' ')
        ft = ft.replace('\xa0', ' ')
        # If the fullText is just a stub (single line with source attribution), strip it
        if '\n' not in ft:
            ft = re.sub(r' {2,}.*$', '', ft).strip()
        else:
            # Multi-paragraph: just collapse double-spaces within each line
            lines = ft.split('\n')
            lines = [re.sub(r' {2,}', ' ', line).strip() for line in lines]
            ft = '\n'.join(lines)
        article['fullText'] = ft

    if 'bullets' in article and isinstance(article['bullets'], list):
        cleaned_bullets = []
        for bullet in article['bullets']:
            if isinstance(bullet, str):
                cleaned_bullets.append(clean_text_strip_attribution(bullet))
            else:
                cleaned_bullets.append(bullet)
        article['bullets'] = cleaned_bullets

    return article


def main():
    print(f"Reading {DATA_JS}...")
    with open(DATA_JS, 'r', encoding='utf-8') as f:
        content = f.read()

    # Extract the JSON object
    match = re.search(r'const\s+DYNAMIC_HUB_DATA\s*=\s*(\{.*\});', content, re.DOTALL)
    if not match:
        print("ERROR: Could not find DYNAMIC_HUB_DATA in data.js")
        return

    data = json.loads(match.group(1))

    # Clean ticker
    if 'ticker' in data and isinstance(data['ticker'], list):
        data['ticker'] = [clean_text_strip_attribution(t) for t in data['ticker']]
        print(f"Cleaned {len(data['ticker'])} ticker entries.")

    # Clean all articles in all timeline slots
    article_count = 0
    if 'timeline' in data:
        for date_key, slots in data['timeline'].items():
            for slot_key, slot_data in slots.items():
                if 'articles' in slot_data and isinstance(slot_data['articles'], list):
                    for i, article in enumerate(slot_data['articles']):
                        slot_data['articles'][i] = clean_article(article)
                        article_count += 1

    print(f"Cleaned {article_count} articles across all timeline slots.")

    # Write back
    json_content = json.dumps(data, indent=2, ensure_ascii=False)
    js_wrapper = f"// Dynamic Hub Data feed generated by real-time automated research.\n// This database is automatically generated 5 times per day.\n\nconst DYNAMIC_HUB_DATA = {json_content};\n"

    with open(DATA_JS, 'w', encoding='utf-8') as f:
        f.write(js_wrapper)
    print(f"Wrote cleaned data to {DATA_JS}")

    # Copy to dist/data.js
    os.makedirs(os.path.dirname(DIST_DATA_JS), exist_ok=True)
    shutil.copy2(DATA_JS, DIST_DATA_JS)
    print(f"Copied cleaned data to {DIST_DATA_JS}")

    print("Done! All &nbsp; entities and source attributions cleaned.")


if __name__ == '__main__':
    main()
