#!/usr/bin/env python3
"""Clean nbsp entities and source attributions from data.js"""
import os
import re
import json
import shutil

WORKSPACE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA_FILE = os.path.join(WORKSPACE, "data.js")
DIST_FILE = os.path.join(WORKSPACE, "dist", "data.js")


def clean_text(text):
    """Replace &nbsp; and \xa0 with space, collapse multi-spaces, strip."""
    if not isinstance(text, str):
        return text
    text = text.replace('\xa0', ' ')
    text = text.replace('&nbsp;', ' ')
    # Collapse 2+ spaces into one
    text = re.sub(r'\s{2,}', ' ', text).strip()
    return text


def clean_text_remove_source(text):
    """Like clean_text, but also removes source attribution after double-spaces.
    
    Google News descriptions look like: 'Title  SourceName'
    After replacing \xa0 with space, that becomes 'Title  SourceName'.
    We strip from the first occurrence of 2+ consecutive spaces onward.
    We need to do this BEFORE collapsing spaces.
    """
    if not isinstance(text, str):
        return text
    text = text.replace('\xa0', ' ')
    text = text.replace('&nbsp;', ' ')
    # Remove source attribution: everything from 2+ spaces to end
    text = re.sub(r'\s{2,}.*$', '', text).strip()
    return text


def clean_article(article):
    """Clean all text fields in an article."""
    if 'title' in article:
        article['title'] = clean_text(article['title'])
    
    if 'bullets' in article and isinstance(article['bullets'], list):
        cleaned_bullets = []
        for b in article['bullets']:
            cleaned = clean_text_remove_source(b)
            if cleaned:
                cleaned_bullets.append(cleaned)
            else:
                cleaned_bullets.append(clean_text(b))
        article['bullets'] = cleaned_bullets
    
    if 'summary' in article:
        cleaned = clean_text_remove_source(article['summary'])
        if cleaned:
            article['summary'] = cleaned
        else:
            article['summary'] = clean_text(article['summary'])
    
    if 'fullText' in article:
        cleaned = clean_text_remove_source(article['fullText'])
        if cleaned:
            article['fullText'] = cleaned
        else:
            # If cleaning removes everything, provide a generic fallback
            source = article.get('author', 'Unknown Source').replace(' Editorial Team', '')
            article['fullText'] = f"Latest real-time briefing from {source} covering the Swedish national football team."
    
    return article


# 1. Read data.js
print(f"Reading {DATA_FILE}...")
with open(DATA_FILE, 'r', encoding='utf-8') as f:
    content = f.read()

match = re.search(r'const\s+DYNAMIC_HUB_DATA\s*=\s*(\{.*\});', content, re.DOTALL)
if not match:
    print("ERROR: Could not parse DYNAMIC_HUB_DATA from data.js")
    exit(1)

data = json.loads(match.group(1))
print("Parsed data.js successfully.")

# 2. Clean ticker
changes = 0
if 'ticker' in data and isinstance(data['ticker'], list):
    for i, headline in enumerate(data['ticker']):
        cleaned = clean_text(headline)
        if cleaned != headline:
            changes += 1
        data['ticker'][i] = cleaned
    print(f"Cleaned {changes} ticker entries.")

# 3. Clean all articles in timeline
article_changes = 0
for date_key, slots in data.get('timeline', {}).items():
    for slot_key, slot_data in slots.items():
        for article in slot_data.get('articles', []):
            old = json.dumps(article)
            clean_article(article)
            if json.dumps(article) != old:
                article_changes += 1

print(f"Cleaned {article_changes} articles across all timeline slots.")

# 4. Write back data.js
json_content = json.dumps(data, indent=2, ensure_ascii=False)
js_wrapper = f"// Dynamic Hub Data feed generated by real-time automated research.\n// This database is automatically generated 5 times per day.\n\nconst DYNAMIC_HUB_DATA = {json_content};\n"

with open(DATA_FILE, 'w', encoding='utf-8') as f:
    f.write(js_wrapper)
print(f"Wrote cleaned data back to {DATA_FILE}")

# 5. Copy to dist/data.js
os.makedirs(os.path.dirname(DIST_FILE), exist_ok=True)
shutil.copy2(DATA_FILE, DIST_FILE)
print(f"Copied data.js to {DIST_FILE}")

print("Done! All nbsp entities and source attributions cleaned.")
