#!/usr/bin/env python3
"""Clean nbsp entities and source attributions from data.js"""
import os
import re
import json
import shutil
import subprocess

WORKSPACE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA_JS = os.path.join(WORKSPACE, "data.js")
DIST_DATA_JS = os.path.join(WORKSPACE, "dist", "data.js")

def clean_text(text):
    """Replace \xa0 and &nbsp; with space, collapse double-spaces, remove source attribution after double-spaces."""
    if not isinstance(text, str):
        return text
    # Replace literal \xa0 (non-breaking space) and &nbsp; entity
    text = text.replace('\xa0', ' ')
    text = text.replace('&nbsp;', ' ')
    # Remove source attribution pattern: double-space followed by source name at end
    # e.g. "Title  SourceName" -> "Title"
    text = re.sub(r'\s{2,}.*$', '', text, flags=re.MULTILINE).strip()
    # Collapse any remaining multiple spaces
    text = re.sub(r'\s{2,}', ' ', text).strip()
    return text

def clean_article(article):
    """Clean bullets, summary, and fullText fields of an article."""
    if 'bullets' in article and isinstance(article['bullets'], list):
        article['bullets'] = [clean_text(b) for b in article['bullets']]
        # Remove empty bullets
        article['bullets'] = [b for b in article['bullets'] if b]
    if 'summary' in article:
        article['summary'] = clean_text(article['summary'])
    if 'fullText' in article:
        article['fullText'] = clean_text(article['fullText'])
    if 'title' in article:
        article['title'] = clean_text(article['title'])
    return article

# 1. Read data.js
print(f"Reading {DATA_JS}...")
with open(DATA_JS, "r", encoding="utf-8") as f:
    content = f.read()

match = re.search(r"const\s+DYNAMIC_HUB_DATA\s*=\s*(\{.*\});", content, re.DOTALL)
if not match:
    print("ERROR: Could not parse DYNAMIC_HUB_DATA from data.js")
    exit(1)

json_str = match.group(1)
data = json.loads(json_str)
print("Parsed JSON successfully.")

# 2. Clean ticker
if 'ticker' in data and isinstance(data['ticker'], list):
    data['ticker'] = [clean_text(t) for t in data['ticker']]
    data['ticker'] = [t for t in data['ticker'] if t]
    print(f"Cleaned {len(data['ticker'])} ticker entries.")

# 3. Clean all timeline articles
article_count = 0
if 'timeline' in data:
    for date_key, slots in data['timeline'].items():
        for slot_key, slot_data in slots.items():
            if 'articles' in slot_data and isinstance(slot_data['articles'], list):
                for i, article in enumerate(slot_data['articles']):
                    slot_data['articles'][i] = clean_article(article)
                    article_count += 1
print(f"Cleaned {article_count} articles across all timeline slots.")

# 4. Clean matchReports if present
if 'matchReports' in data:
    for key, report in data['matchReports'].items():
        if isinstance(report, dict):
            data['matchReports'][key] = clean_article(report)

# 5. Write back data.js
json_content = json.dumps(data, indent=2, ensure_ascii=False)
js_wrapper = f"// Dynamic Hub Data feed generated by real-time automated research.\n// This database is automatically generated 5 times per day.\n\nconst DYNAMIC_HUB_DATA = {json_content};\n"

with open(DATA_JS, "w", encoding="utf-8") as f:
    f.write(js_wrapper)
print(f"Wrote cleaned data back to {DATA_JS}")

# 6. Copy to dist/data.js
os.makedirs(os.path.dirname(DIST_DATA_JS), exist_ok=True)
shutil.copy2(DATA_JS, DIST_DATA_JS)
print(f"Copied to {DIST_DATA_JS}")

print("\nDone! Data cleaned successfully.")
