#!/usr/bin/env python3
import sys
import os
import re
import json
import random
from datetime import datetime
from zoneinfo import ZoneInfo

TARGET_FILE = os.path.join(os.path.dirname(os.path.dirname(__file__)), "data.js")

existing_data = {"banter": []}

try:
    with open(TARGET_FILE, "r", encoding="utf-8") as f:
        content = f.read()
        match = re.search(r"const\s+DYNAMIC_HUB_DATA\s*=\s*(\{.*\});", content, re.DOTALL)
        if match:
            existing_data = json.loads(match.group(1))
            if "banter" not in existing_data:
                existing_data["banter"] = []
except Exception as e:
    print(f"Error reading data.js: {e}")
    sys.exit(1)

players = [
    {"name": "Victor Lindelöf", "isCaptain": True},
    {"name": "Viktor Gyökeres", "isCaptain": False},
    {"name": "Alexander Isak", "isCaptain": False},
    {"name": "Dejan Kulusevski", "isCaptain": False},
    {"name": "Lucas Bergvall", "isCaptain": False},
    {"name": "Carl Starfelt", "isCaptain": False},
    {"name": "Yasin Ayari", "isCaptain": False},
    {"name": "Emil Krafth", "isCaptain": False},
    {"name": "Jesper Karlsson", "isCaptain": False},
    {"name": "Kristoffer Olsson", "isCaptain": False}
]

messages = [
    "God morgon! Är alla redo för dagens första pass?",
    "Vem tog mitt kaffe i matsalen?!",
    "Träningen idag var intensiv, precis som det ska vara.",
    "Vi ses i lobbyn kl 10. Glöm inte passet!",
    "Bosse, stäng av musiken nu, måste sova! 😂",
    "Vilken stämning det är här i lägret. Framåt Sverige!",
    "Någon som är sugen på lite FIFA ikväll?",
    "Hörni, samling i teorisalen om 10 minuter.",
    "Vilket mål på träningen! Jag tror jag hittat formen.",
    "Bara några dagar kvar nu. Känner ni peppen?",
    "Dags att vila. Viktig dag imorgon.",
    "Har alla koll på schemat för morgondagen?",
    "Vi ska visa hela världen vad vi går för!",
    "Bra jobbat på planen idag, grabbar.",
    "Ska vi spela padel när vi får ledigt?"
]

now = datetime.now(ZoneInfo("America/New_York"))

new_banters = []
selected_players = random.sample(players, 5)
selected_messages = random.sample(messages, 5)

for i in range(5):
    p = selected_players[i]
    minute = now.minute + i
    hour = now.hour
    if minute >= 60:
        minute -= 60
        hour = (hour + 1) % 24
    sim_time = f"{hour:02d}:{minute:02d}"
    
    new_banters.append({
        "sender": p["name"],
        "avatar": "🇸🇪",
        "text": selected_messages[i],
        "time": sim_time,
        "isCaptain": p["isCaptain"]
    })

existing_data["banter"].extend(new_banters)

try:
    with open(TARGET_FILE, "w", encoding="utf-8") as f:
        json_content = json.dumps(existing_data, indent=2, ensure_ascii=False)
        js_wrapper = f"// Dynamic Hub Data feed generated by real-time automated research.\n// This database is automatically generated 5 times per day.\n\nconst DYNAMIC_HUB_DATA = {json_content};\n"
        f.write(js_wrapper)
    print("SUCCESS: appended 5 new banter messages.")
except Exception as e:
    print(f"Error writing: {e}")
