#!/usr/bin/env python3
import sys
import os
import re
import json
import random
from datetime import datetime
from zoneinfo import ZoneInfo

TARGET_FILE = os.path.join(os.path.dirname(os.path.dirname(__file__)), "data.js")

existing_data = {"banter": []}

try:
    with open(TARGET_FILE, "r", encoding="utf-8") as f:
        content = f.read()
        match = re.search(r"const\s+DYNAMIC_HUB_DATA\s*=\s*(\{.*\});", content, re.DOTALL)
        if match:
            existing_data = json.loads(match.group(1))
            if "banter" not in existing_data:
                existing_data["banter"] = []
except Exception as e:
    print(f"Error reading data.js: {e}")
    sys.exit(1)

players = [
    {"name": "Harry Kane", "isCaptain": True},
    {"name": "Declan Rice", "isCaptain": False},
    {"name": "Jude Bellingham", "isCaptain": False},
    {"name": "Bukayo Saka", "isCaptain": False},
    {"name": "Phil Foden", "isCaptain": False},
    {"name": "Jordan Pickford", "isCaptain": False},
    {"name": "Trent Alexander-Arnold", "isCaptain": False},
    {"name": "Cole Palmer", "isCaptain": False},
    {"name": "Ollie Watkins", "isCaptain": False},
    {"name": "John Stones", "isCaptain": False}
]

messages = [
    "Morning lads! Just checking in.",
    "Anyone up for some darts in the games room?",
    "That training session was proper intense.",
    "Bags packed and ready. Let's get it.",
    "Who's got control of the playlist today? Needs sorting out.",
    "Just landed. Straight to St George's Park.",
    "Can't wait to get back out there. Focus is 100%.",
    "Someone tell Jude to stop showing off in the rondo 😂",
    "Need a proper cup of tea before the tactical meeting.",
    "Rest up tonight boys. Massive week ahead.",
    "Who saw that strike in training?! Unbelievable.",
    "Don't forget the media duties at 2pm lads.",
    "Ready to make this year ours. Stick together.",
    "Let's bring it home this time! 🏴󠁧󠁢󠁥󠁮󠁧󠁿💪",
    "Pitch is looking immaculate out there.",
    "Early night for me. Need the recovery."
]

now = datetime.now(ZoneInfo("America/New_York"))

new_banters = []
selected_players = random.sample(players, 5)
selected_messages = random.sample(messages, 5)

for i in range(5):
    p = selected_players[i]
    minute = now.minute + i
    hour = now.hour
    if minute >= 60:
        minute -= 60
        hour = (hour + 1) % 24
    sim_time = f"{hour:02d}:{minute:02d}"
    
    new_banters.append({
        "sender": p["name"],
        "avatar": "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
        "text": selected_messages[i],
        "time": sim_time,
        "isCaptain": p["isCaptain"]
    })

existing_data["banter"].extend(new_banters)

try:
    with open(TARGET_FILE, "w", encoding="utf-8") as f:
        json_content = json.dumps(existing_data, indent=2, ensure_ascii=False)
        js_wrapper = f"// Dynamic Hub Data feed generated by real-time automated research.\n// This database is automatically generated 5 times per day.\n\nconst DYNAMIC_HUB_DATA = {json_content};\n"
        f.write(js_wrapper)
    print("SUCCESS: appended 5 new banter messages.")
except Exception as e:
    print(f"Error writing: {e}")
