#!/usr/bin/env python3
import sys
import os
import re
import json
import random
from datetime import datetime
from zoneinfo import ZoneInfo

TARGET_FILE = os.path.join(os.path.dirname(os.path.dirname(__file__)), "data.js")

existing_data = {"banter": []}

try:
    with open(TARGET_FILE, "r", encoding="utf-8") as f:
        content = f.read()
        match = re.search(r"const\s+DYNAMIC_HUB_DATA\s*=\s*(\{.*\});", content, re.DOTALL)
        if match:
            existing_data = json.loads(match.group(1))
            if "banter" not in existing_data:
                existing_data["banter"] = []
except Exception as e:
    print(f"Error reading data.js: {e}")
    sys.exit(1)

players = [
    {"name": "Christian Pulisic", "isCaptain": True},
    {"name": "Weston McKennie", "isCaptain": False},
    {"name": "Folarin Balogun", "isCaptain": False},
    {"name": "Tyler Adams", "isCaptain": False},
    {"name": "Antonee Robinson", "isCaptain": False},
    {"name": "Tim Weah", "isCaptain": False},
    {"name": "Matt Turner", "isCaptain": False},
    {"name": "Gio Reyna", "isCaptain": False},
    {"name": "Ricardo Pepi", "isCaptain": False},
    {"name": "Yunus Musah", "isCaptain": False}
]

messages = [
    "Anyone got an extra phone charger? Left mine at the hotel.",
    "The altitude here is no joke. Lungs are burning!",
    "Who's up for some FIFA tonight in my room?",
    "Poch's tactical session today was intense. Mind blown.",
    "Bags are packed! Who's ready?",
    "Just saw the training kit. Actually looks fire this year.",
    "Can't wait to hear the fans tomorrow. The Outlaws always bring it.",
    "Need more ranch dressing at the buffet immediately.",
    "Who took my boots?! Not funny guys.",
    "Early night for me. Big day tomorrow.",
    "Coffee in the lobby if anyone is awake.",
    "Anyone else still jetlagged?",
    "These new training balls are flying everywhere.",
    "Rest up boys, big session tomorrow.",
    "Are we wearing the white or blue kits tomorrow?",
    "Just watched the film from training. We look sharp.",
    "What time is the team meeting again?",
    "Someone tell Weston to stop singing in the showers.",
    "Ready to make history this summer. Let's go!"
]

now = datetime.now(ZoneInfo("America/New_York"))

new_banters = []
selected_players = random.sample(players, 5)
selected_messages = random.sample(messages, 5)

for i in range(5):
    p = selected_players[i]
    minute = now.minute + i
    hour = now.hour
    if minute >= 60:
        minute -= 60
        hour = (hour + 1) % 24
    sim_time = f"{hour:02d}:{minute:02d}"
    
    new_banters.append({
        "sender": p["name"],
        "avatar": "🇺🇸",
        "text": selected_messages[i],
        "time": sim_time,
        "isCaptain": p["isCaptain"]
    })

existing_data["banter"].extend(new_banters)

try:
    with open(TARGET_FILE, "w", encoding="utf-8") as f:
        json_content = json.dumps(existing_data, indent=2, ensure_ascii=False)
        js_wrapper = f"// Dynamic Hub Data feed generated by real-time automated research.\n// This database is automatically generated 5 times per day.\n\nconst DYNAMIC_HUB_DATA = {json_content};\n"
        f.write(js_wrapper)
    print("SUCCESS: appended 5 new banter messages.")
except Exception as e:
    print(f"Error writing: {e}")
